server:
  port: 8282
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ks
    password: sowmya
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  activemq:
    broker-url: tcp://localhost:61616

#Fileproperties
app:
  source: C:/Training/input?fileName=Test_input.txt
  destination: C:/Training/output/
  messageSource: C:/Training/input?fileName=JMSMessage.txt
  messageDestination: C:/Training/output/

#JMS Properties
camel:
  component:
    activemq:
      broker-url: tcp://localhost:61616